# RedHat related OSs
- name: create epel.repo
  action: template src=ganglia/templates/epel.repo dest=/etc/yum.repos.d/epel.repo 
  only_if: $redhat_os

- name: Yum install $item
  action: yum pkg=$item state=installed
  with_items:
    - ganglia-gmond
    - ganglia-gmetad
  only_if: $redhat_os

- name: configure gmond (REL6)
  action: template src=ganglia/templates/gmond.conf dest=/etc/ganglia/gmond.conf owner=root group=root
  notify:
      - restart gmond
  only_if: $redhat6_os

- name: configure gmond (REL5)
  action: template src=ganglia/templates/gmond.old.conf dest=/etc/gmond.conf owner=root group=root
  notify:
      - restart gmond
  only_if: $redhat5_os
      
- name: start gmond
  action: service name=gmond state=running
  only_if: $redhat_os
  
- name: configure gmetad (REL5)
  action: template src=ganglia/templates/gmetad.conf dest=/etc/gmetad.conf owner=root group=root
  notify:
      - restart gmetad
  only_if: $redhat5_os
  
- name: configure gmetad (REL6)
  action: template src=ganglia/templates/gmetad.conf dest=/etc/ganglia/gmetad.conf owner=root group=root
  notify:
      - restart gmetad
  only_if: $redhat6_os
  
- name: start gmetad
  action: service name=gmetad state=running
  only_if: $redhat_os

# Debian related OSs
- name: Apt install $item
  action: apt pkg=$item state=installed
  with_items:
    - ganglia-monitor
    - gmetad
  only_if: $debian_os
  
- name: configure ganglia-monitor
  action: template src=ganglia/templates/gmond.conf dest=/etc/ganglia/gmond.conf owner=root group=root
  notify:
      - restart ganglia-monitor
  only_if: $debian_os
  
- name: configure gmetad
  action: template src=ganglia/templates/gmetad.conf dest=/etc/ganglia/gmetad.conf owner=root group=root
  notify:
      - restart gmetad-dev
  only_if: $debian_os