- name: restart gmetad
  action: service name=gmetad state=restarted

- name: restart gmond
  action: service name=gmond state=restarted
  
- name: restart ganglia-monitor
  action: service name=ganglia-monitor state=restarted pattern=/usr/sbin/gmond
  
- name: restart gmetad-dev
  action: service name=gmetad state=restarted pattern=/usr/sbin/gmetad